### ISSUE TITLE
Will it work for negative axes?

### ISSUE THREAD

**Issue by kranti-up** [andrewrgarcia/voxelmap#8]
HI,
Thank you for the library. Is it possible to plot voxels on negative axes? I have some points on negative x, y and z axes. Is it possible to plot them? If so, can you please share an example?

Thank you

**Comment by andrewrgarcia** [comment]
@kranti-up,

A new version has been deployed to resolve this Issue. Run `pip install --upgrade voxelmap` and then try the following Python code:
```python 
import voxelmap as vxm
import numpy as np

data = vxm.Data()          
data.xyz = np.random.randint(-1,1,(10,3))+np.random.random((10,3))     # random x,y,z locs for 10 voxels
data.sparsity = 5                       # spaces out coordinates 
cubes = data.importdata('coords')

model = vxm.Model(cubes)     
model.hashblocks = data.hashblocks      # transfer colors from Data class to Model class 
print(data.xyz)                              # print the xyz coordinate data
model.draw('voxels')                   # draw the model from that data
```
This will give you an output which looks something like this:
```
[Out]
[[ 0.09810283 -0.05707691 -0.40492372]
 [-0.85035545 -0.61693541  0.03495741]
 [ 0.0542932  -0.20244378  0.09935272]
 [-0.74850127 -0.50574033  0.13398549]
 [-0.87515848 -0.3319057  -0.46527974]
 [-0.16978636  0.59375739 -0.31659409]
 [-0.2467994   0.61286223 -0.67413402]
 [-0.69552436 -0.32921826 -0.68783246]
 [ 0.34158347  0.66220869 -0.26698782]
 [-0.12140307 -0.56846614 -0.21772612]]
```
![Figure_1](https://user-images.githubusercontent.com/10375211/205191281-895fb7f5-2548-4262-94b9-695d06378104.png)

As you can see, the xyz data also has negative xyz locations. Be wary of the `data.sparsity` variable. Will close this Issue. 
-Andrew

**Comment by andrewrgarcia** [comment]
Usage also found on new [voxelmap documentation]
(https://colab.research.google.com/drive/1RMEMgZHlk_tKAzfS4QfXLJV9joDgdh8N?usp=sharing) under "Draw voxels from coordinate arrays" section
